//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amiliur.figforms.web.blazor.Components.Standard.Buttons {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Buttons {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("amiliur.figforms.web.blazor.Components.Standard.Buttons.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FigSaveButtonDefaultText {
            get {
                return ResourceManager.GetString("FigSaveButtonDefaultText", resourceCulture);
            }
        }
        
        internal static string FigSaveButtonDefaultBusyText {
            get {
                return ResourceManager.GetString("FigSaveButtonDefaultBusyText", resourceCulture);
            }
        }
        
        internal static string FigCancelButtonBusyText {
            get {
                return ResourceManager.GetString("FigCancelButtonBusyText", resourceCulture);
            }
        }
        
        internal static string FigCancelButtonText {
            get {
                return ResourceManager.GetString("FigCancelButtonText", resourceCulture);
            }
        }
        
        internal static string FigAddNewButtonBusyText {
            get {
                return ResourceManager.GetString("FigAddNewButtonBusyText", resourceCulture);
            }
        }
        
        internal static string FigAddNewButtonText {
            get {
                return ResourceManager.GetString("FigAddNewButtonText", resourceCulture);
            }
        }
    }
}
